package com.meng.device.mapper;

import com.meng.device.dao.SbInfo;
import com.meng.device.dao.SbInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SbInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    long countByExample(SbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int deleteByExample(SbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int insert(SbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int insertSelective(SbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    List<SbInfo> selectByExample(SbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    SbInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SbInfo record, @Param("example") SbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SbInfo record, @Param("example") SbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SbInfo record);
}