package com.meng.device.mapper;

import com.meng.device.dao.Sblx;
import com.meng.device.dao.SblxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SblxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    long countByExample(SblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int deleteByExample(SblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sblxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int insert(Sblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int insertSelective(Sblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    List<Sblx> selectByExample(SblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    Sblx selectByPrimaryKey(Integer sblxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sblx record, @Param("example") SblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sblx record, @Param("example") SblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sblx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sblx record);
}