package com.meng.device.dao;

import java.util.Date;

public class SbInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.sbname
     *
     * @mbg.generated
     */
    private String sbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.sbscrq
     *
     * @mbg.generated
     */
    private Date sbscrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.sbwyrxb
     *
     * @mbg.generated
     */
    private String sbwyrxb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.sbjg
     *
     * @mbg.generated
     */
    private Integer sbjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbinfo.sblx_id
     *
     * @mbg.generated
     */
    private Integer sblxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.id
     *
     * @return the value of sbinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.id
     *
     * @param id the value for sbinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.sbname
     *
     * @return the value of sbinfo.sbname
     *
     * @mbg.generated
     */
    public String getSbname() {
        return sbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.sbname
     *
     * @param sbname the value for sbinfo.sbname
     *
     * @mbg.generated
     */
    public void setSbname(String sbname) {
        this.sbname = sbname == null ? null : sbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.sbscrq
     *
     * @return the value of sbinfo.sbscrq
     *
     * @mbg.generated
     */
    public Date getSbscrq() {
        return sbscrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.sbscrq
     *
     * @param sbscrq the value for sbinfo.sbscrq
     *
     * @mbg.generated
     */
    public void setSbscrq(Date sbscrq) {
        this.sbscrq = sbscrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.sbwyrxb
     *
     * @return the value of sbinfo.sbwyrxb
     *
     * @mbg.generated
     */
    public String getSbwyrxb() {
        return sbwyrxb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.sbwyrxb
     *
     * @param sbwyrxb the value for sbinfo.sbwyrxb
     *
     * @mbg.generated
     */
    public void setSbwyrxb(String sbwyrxb) {
        this.sbwyrxb = sbwyrxb == null ? null : sbwyrxb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.sbjg
     *
     * @return the value of sbinfo.sbjg
     *
     * @mbg.generated
     */
    public Integer getSbjg() {
        return sbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.sbjg
     *
     * @param sbjg the value for sbinfo.sbjg
     *
     * @mbg.generated
     */
    public void setSbjg(Integer sbjg) {
        this.sbjg = sbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbinfo.sblx_id
     *
     * @return the value of sbinfo.sblx_id
     *
     * @mbg.generated
     */
    public Integer getSblxId() {
        return sblxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbinfo.sblx_id
     *
     * @param sblxId the value for sbinfo.sblx_id
     *
     * @mbg.generated
     */
    public void setSblxId(Integer sblxId) {
        this.sblxId = sblxId;
    }
}