package com.meng.device.dao;

public class Sblx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sblx.sblx_id
     *
     * @mbg.generated
     */
    private Integer sblxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sblx.sblx
     *
     * @mbg.generated
     */
    private String sblx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sblx.sblx_id
     *
     * @return the value of sblx.sblx_id
     *
     * @mbg.generated
     */
    public Integer getSblxId() {
        return sblxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sblx.sblx_id
     *
     * @param sblxId the value for sblx.sblx_id
     *
     * @mbg.generated
     */
    public void setSblxId(Integer sblxId) {
        this.sblxId = sblxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sblx.sblx
     *
     * @return the value of sblx.sblx
     *
     * @mbg.generated
     */
    public String getSblx() {
        return sblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sblx.sblx
     *
     * @param sblx the value for sblx.sblx
     *
     * @mbg.generated
     */
    public void setSblx(String sblx) {
        this.sblx = sblx == null ? null : sblx.trim();
    }
}